## Docker image for testing inside a cluster :test image tag
FROM golang:1.13.11-stretch AS builder

WORKDIR /go/src/github.com/joshisumit/eks-dns-troubleshooter/

COPY . .

RUN make build

ENTRYPOINT ["/go/src/github.com/joshisumit/eks-dns-troubleshooter/eks-dnshooter"]