FROM golang:alpine AS builder

LABEL version="0.1" maintainer="sumitjoshi024@gmail.com"

# Set necessary environment variables
ENV GO111MODULE=on \
    GOOS=linux \
    GOARCH=amd64 \
    CGO_ENABLED=0
    
WORKDIR /build

# copy and download dependency using go mod
COPY go.mod go.sum ./
RUN go mod download

# copy the code into container
COPY . ./

# Build the application
RUN go build -o eks-dnshooter ./cmd/

# Use amazonlinux:2 as final image
FROM amazonlinux:2

WORKDIR /app

RUN yum update -y && \
    yum install -y bind-utils

COPY --from=builder /build/eks-dnshooter /app/

ENTRYPOINT ["/app/eks-dnshooter"]