---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-dns-ts
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: eks-dns-troubleshooter
  name: eks-dns-ts
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
      - services
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: eks-dns-troubleshooter  
  name: eks-dns-ts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-dns-ts
subjects:
- kind: ServiceAccount
  name: eks-dns-ts
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eks-dns-troubleshooter
  name: eks-dns-troubleshooter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goclient-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: goclient-test
    spec:
      containers:
      - image: in-cluster:v49
        name: in-cluster
        resources: {}
        env:
          - name: EKS_DNS_LOGLEVEL
            value: DEBUG
        imagePullPolicy: IfNotPresent
      serviceAccountName: eks-dns-ts
status: {}
