---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-dns-ts
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: goclient-test
  name: goclient-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goclient-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: goclient-test
    spec:
      containers:
      - image: in-cluster:v12
        name: in-cluster
        resources: {}
        imagePullPolicy: IfNotPresent
      serviceAccountName: eks-dns-ts
status: {}
