apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-dns-troubleshooter
  name: eks-dns-troubleshooter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-dns-troubleshooter
  template:
    metadata:
      labels:
        app: eks-dns-troubleshooter
    spec:
      containers:
      - image: sumitj/eks-dnshooter:v1.1.0
        name: eks-dns-troubleshooter
        env:
          - name: EKS_DNS_LOGLEVEL
            value: DEBUG
      serviceAccountName: eks-dns-ts
