---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: eks-dns-troubleshooter
  name: eks-dns-ts
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: eks-dns-troubleshooter
  name: eks-dns-ts
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/status
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: eks-dns-troubleshooter
  name: eks-dns-ts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-dns-ts
subjects:
- kind: ServiceAccount
  name: eks-dns-ts
  namespace: default
